application: easywebsocket
version: 1
runtime: python
api_version: 1

handlers:
- url: /iframe
  static_dir: iframe

- url: /examples
  static_dir: examples

- url: /.*
  script: AppEngine/easyWebSocket.py
