application: easywebsocket
version: 1
runtime: python
api_version: 1

handlers:
- url: /web
  static_dir: web

- url: /examples
  static_dir: examples

- url: /.*
  script: AppEngine/easyWebSocket.py
