# Google AppEngine configuration file
# for easywebsocket-gapp.js only

application: easywebsocket
version: 1
runtime: python
api_version: 1

handlers:
- url: /gapp/iframe
  static_dir: gapp/iframe

- url: /.*
  script: gapp/AppEngine/easyWebSocket.py
